### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by d0nmiguelo** [caleb-snow-cbm/MCP2518FD-esp32#1]
Hi, I'm trying to build the example project, but when I do "idf.py build" I get this:

Executing action: all (aliases: build)
Running ninja in directory /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build
Executing "ninja all"...
[1/1] cd /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build/bootloader/esp-idf/esptool_py && /home/migue...et 0x8000 bootloader 0x1000 /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build/bootloader/bootloader.bin
Bootloader binary size 0x6580 bytes. 0xa80 bytes (9%) free.
[4/12] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj 
/home/miguelangel/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/xtensa-esp32-elf-g++ -DESP_PLATFORM -DIDF_VER=\"v5.4.1-dirty\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build/config -I/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/main -I/home/miguelangel/esp/v5.4.1/esp-idf/components/newlib/platform_include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/config/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/config/include/freertos -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/config/xtensa/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/esp_additions/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/include/soc -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/include/soc/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/dma/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/ldo/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/debug_probe/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32/. -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/heap/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/heap/tlsf -I/home/miguelangel/esp/v5.4.1/esp-idf/components/log/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/esp32/register -I/home/miguelangel/esp/v5.4.1/esp-idf/components/hal/platform_port/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/hal/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/hal/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/esp32/include/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_common/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_system/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_system/port/soc -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_system/port/include/private -I/home/miguelangel/esp/v5.4.1/esp-idf/components/xtensa/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/xtensa/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/xtensa/deprecated_include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/include/apps -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/include/apps/sntp -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/lwip/src/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/freertos/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include/arch -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include/sys -I/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_driver_gpio/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_driver_spi/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_pm/include -mlongcalls -Wno-frame-address  -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-error=extra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fno-shrink-wrap -fmacro-prefix-map=/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32=. -fmacro-prefix-map=/home/miguelangel/esp/v5.4.1/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu++2b -fno-exceptions -fno-rtti -fuse-cxa-atexit -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj -c /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/main/main.cpp
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/main/main.cpp:10:24: error: 'constinit' variable 'mcp' does not have a constant initializer
   10 | constinit cbm::MCP2518 mcp;
      |                        ^~~
In file included from /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/main/main.cpp:8:
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/main/main.cpp:10:24:   in 'constexpr' expansion of 'cbm::MCP2518()'
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:163:50:   in 'constexpr' expansion of 'cbm::MCP2518::Registers::getFifoConfigs()'
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:1692:35: error: accessing 'cbm::MCP2518::Registers::C1FIFOCON::<unnamed union>::<anonymous>' member instead of initialized 'cbm::MCP2518::Registers::C1FIFOCON::<unnamed union>::bits' member in constant expression
 1692 |                 configs[i].PLSIZE = it - cPayloadSizes.begin();
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:1597:17: note: 'cbm::MCP2518::Registers::C1FIFOCON::<unnamed union>::<anonymous>' does not implicitly begin its lifetime because 'cbm::MCP2518::Registers::C1FIFOCON::<unnamed union>::<unnamed struct>' does not have a non-deleted trivial default constructor, use 'std::construct_at' instead
 1597 |                 struct {
      |                 ^~~~~~
[5/12] Building CXX object esp-idf/MCP2518FD/CMakeFiles/__idf_MCP2518FD.dir/MCP2518.cpp.obj
FAILED: esp-idf/MCP2518FD/CMakeFiles/__idf_MCP2518FD.dir/MCP2518.cpp.obj 
/home/miguelangel/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/xtensa-esp32-elf-g++ -DESP_PLATFORM -DIDF_VER=\"v5.4.1-dirty\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build/config -I/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD -I/home/miguelangel/esp/v5.4.1/esp-idf/components/newlib/platform_include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/config/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/config/include/freertos -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/config/xtensa/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos -I/home/miguelangel/esp/v5.4.1/esp-idf/components/freertos/esp_additions/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/include/soc -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/include/soc/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/dma/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/ldo/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/debug_probe/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32/. -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/heap/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/heap/tlsf -I/home/miguelangel/esp/v5.4.1/esp-idf/components/log/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/soc/esp32/register -I/home/miguelangel/esp/v5.4.1/esp-idf/components/hal/platform_port/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/hal/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/hal/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/esp32/include/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_rom/esp32 -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_common/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_system/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_system/port/soc -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_system/port/include/private -I/home/miguelangel/esp/v5.4.1/esp-idf/components/xtensa/esp32/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/xtensa/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/xtensa/deprecated_include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/include/apps -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/include/apps/sntp -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/lwip/src/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/freertos/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include/arch -I/home/miguelangel/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include/sys -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_driver_gpio/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_driver_spi/include -I/home/miguelangel/esp/v5.4.1/esp-idf/components/esp_pm/include -mlongcalls -Wno-frame-address  -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-error=extra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fno-shrink-wrap -fmacro-prefix-map=/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32=. -fmacro-prefix-map=/home/miguelangel/esp/v5.4.1/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu++2b -fno-exceptions -fno-rtti -fuse-cxa-atexit -MD -MT esp-idf/MCP2518FD/CMakeFiles/__idf_MCP2518FD.dir/MCP2518.cpp.obj -MF esp-idf/MCP2518FD/CMakeFiles/__idf_MCP2518FD.dir/MCP2518.cpp.obj.d -o esp-idf/MCP2518FD/CMakeFiles/__idf_MCP2518FD.dir/MCP2518.cpp.obj -c /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.cpp
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.cpp: In member function 'void cbm::MCP2518::begin(const Config&)':
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.cpp:108:5: warning: missing initializer for member 'spi_device_interface_config_t::sample_point' [-Wmissing-field-initializers]
  108 |     };
      |     ^
In file included from /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.cpp:26:
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp: In member function 'void cbm::MCP2518::configDefault()':
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.cpp:364:98:   in 'constexpr' expansion of 'cbm::MCP2518::Registers::C1NBTCFG(cbm::MCP2518::BitTiming(((int)cbm::MCP2518::cSysClockHz), ((int)cbm::cDefaultNominalBitrate), 1))'
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:868:21: error: accessing uninitialized member 'cbm::MCP2518::Registers::C1NBTCFG::<unnamed union>::<anonymous>'
  868 |                 SJW = bt.SJW - 1;
      |                 ~~~~^~~~~~~~~~~~
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:876:17: note: 'cbm::MCP2518::Registers::C1NBTCFG::<unnamed union>::<anonymous>' does not implicitly begin its lifetime because 'cbm::MCP2518::Registers::C1NBTCFG::<unnamed union>::<unnamed struct>' does not have a non-deleted trivial default constructor, use 'std::construct_at' instead
  876 |                 struct {
      |                 ^~~~~~
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.cpp:368:101:   in 'constexpr' expansion of 'cbm::MCP2518::Registers::C1DBTCFG(cbm::MCP2518::BitTiming(((int)cbm::MCP2518::cSysClockHz), ((int)cbm::cDefaultDataBitrate), 0))'
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:910:21: error: accessing uninitialized member 'cbm::MCP2518::Registers::C1DBTCFG::<unnamed union>::<anonymous>'
  910 |                 SJW = bt.SJW - 1;
      |                 ~~~~^~~~~~~~~~~~
/home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/components/MCP2518FD/MCP2518.hpp:919:17: note: 'cbm::MCP2518::Registers::C1DBTCFG::<unnamed union>::<anonymous>' does not implicitly begin its lifetime because 'cbm::MCP2518::Registers::C1DBTCFG::<unnamed union>::<unnamed struct>' does not have a non-deleted trivial default constructor, use 'std::construct_at' instead
  919 |                 struct {
      |                 ^~~~~~
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build/log/idf_py_stderr_output_983581 and /home/miguelangel/Documents/tucar/repos/MCP2518FD-esp32/build/log/idf_py_stdout_output_983581

I didn't make any change in the code.

**Comment by d0nmiguelo** [comment]
It was because of the version of espidf. I was using v5.4 and it works with v5.3.
